all:

	clear
	g++ p107.cpp -o p107 -lm -lcrypt -O2 -pipe -DONLINE_JUDGE

remove:

	rm p107

run:

	./p107 < inputsOriginal.txt

run2:

	./p107 < inputs2.txt

run3:

	./p107 < inputs3.txt

runTest:

	./p107 < inputs3.txt > output.txt
	diff output.txt output3.txt
